### ISSUE TITLE
字段含义：click&keyword&caption的字段含义

### ISSUE THREAD

**Issue by catmint999** [KuaiSAR/KuaiSAR.github.io#1]
您好，想请教一下这个数据集中几个字段含义的问题，灰常感谢！
1. rec_inter.csv 中click是指什么？单列短视频推荐也有定义click吗？
2. src_inter中的keyword和item_features分别指什么？两者的字段是用同一映射关系映射成编码吗？

**Comment by Ethan00Si** [comment]
click的含义可以参考KuaiRand数据集(https://kuairand.com/ )中的注释：“A binary feedback signal. In the two-column UI, it indicates a click; In the single-column UI, it means valid_play: which equals 1 when: play_time_ms >= duration_ms if duration_ms <= 7,000 ms, or play_time_ms > 7,000 ms if duration_ms > 7,000 ms.” 。推荐系统科研论文一般预测用户的隐式反馈，即用户是否点击物品，我们推荐用这个label作为implicit feedback的标签。短视频场景下"是否点击"的定义比较复杂，和具体业务相关，可以简单地将click当作implicit feedback。

keyword是搜索的query的切词后的结果，比如“中国的首都在哪里” keyword是 【中国，的，首都，在，哪里】，再hash成为整数。

caption是视频的介绍文本，快手里的视频除了titile还有caption，打开app浏览视频，下方会有标题、描述文案。

两者映射出的编码相同。
